<?php

namespace AppBundle\Repository;

/**
 * VinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinRepository extends \Doctrine\ORM\EntityRepository
{
}
