<?php

namespace AppBundle\Repository;

/**
 * ExposantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExposantRepository extends \Doctrine\ORM\EntityRepository
{
}
